In [2]:
import pandas as pd
import numpy as np

In [3]:
df_initial = pd.read_csv('Coin.csv')
df_new = pd.read_csv('Coin_new.csv')

In [4]:
df_initial

,id,address,name,symbol,description,totalSupply,totalVolume,volume24h,createdAt,creatorAddress,...,blurhash,creatorEarnings,mediumImageUrl,mimeType,originalImageUrl,previewImageUrl,creatorProfileAvatarBlurhash,creatorProfileAvatarUrl,creatorProfileHandle,creatorProfileId
0,R3JhcGhRTFpvcmEyMFRva2VuOkJBU0UtTUFJTk5FVC4weD...,0x0400436a9122d8be02d648fb7c68382c665963a9,Cherepaxa,Cherepaxa,NaN,1000000000,1.89,1.91,2025-03-15 06:56:45,0xd0db2fe525f49f59e29fc2e69765572b14e3c1bd,...,eQ9*$lsm9oM|flw8ozNPWBjXAMR+$]s-acIeWExmt3WYRX...,"[{""amount"":{""currency"":{""address"":""0x000000000...",https://media.decentralized-content.com/-/rs:f...,image/jpeg,ipfs://bafybeid4wetigz3tlj56jjrddbr2rezxarvhrt...,https://media.decentralized-content.com/-/rs:f...,e78=G#8y0L.6$Q.RR6jZXls:JQtQw1S1XSaKW;tRrsM{D*...,https://media.decentralized-content.com/-/rs:f...,0xb264...5368,R3JhcGhRTEFjY291bnRQcm9maWxlOjY1NjZhMTllODhhZT...
1,R3JhcGhRTFpvcmEyMFRva2VuOkJBU0UtTUFJTk5FVC4weD...,0x04031a54170e8799083e97eb7014eb9768fb3099,"3/7/25, 9:28 PM","3/7/25, 9:28 PM",BomBom,1000000000,0.24,0.24,2025-03-07 18:28:59,0x2377b5952a144805bfeace1af8437e5d3eed51bd,...,eKG[1aD*^+RjNu0Lx]n$W;o3IWRjOUt7RQtRx[W=VsxsEL...,"[{""amount"":{""currency"":{""address"":""0x000000000...",https://media.decentralized-content.com/-/rs:f...,image/jpeg,ipfs://bafybeiag4ywz7dkgq7l6cxl2x7nb4j3j3qdbcn...,https://media.decentralized-content.com/-/rs:f...,eaH-GP^%0g9bn$9aM|%2t7j[NbWVs.s.ofRkR*WCWBR*WB...,https://media.decentralized-content.com/-/rs:f...,truebombaster,R3JhcGhRTEFjY291bnRQcm9maWxlOjY1YjdjZjIxNmY0YW...
2,R3JhcGhRTFpvcmEyMFRva2VuOkJBU0UtTUFJTk5FVC4weD...,0x04118d0e2e0f8de387579b2ee91d8b9022c52e8d,39703,39703,RBY,1000000000,0.22,0.22,2025-03-05 08:55:55,0xab12e16bf63cdc796eb7ddab9424767b5fb45467,...,"e46aL:J%0#^P-U[vM}FZ$Q$QFtR*,tNuOB5ls:^5EMI;I;...","[{""amount"":{""currency"":{""address"":""0x000000000...",https://media.decentralized-content.com/-/rs:f...,image/jpeg,ipfs://bafybeihptknxrdpak2xyp6aqzlxwuely4w7wwk...,https://media.decentralized-content.com/-/rs:f...,"e46aL:J%0#^P-U[vM}FZ$Q$QFtR*,tNuOB5ls:^5EMI;I;...",https://media.decentralized-content.com/-/rs:f...,robbinhood,R3JhcGhRTEFjY291bnRQcm9maWxlOjY3YzgxMTE2MTQ3Yz...
3,R3JhcGhRTFpvcmEyMFRva2VuOkJBU0UtTUFJTk5FVC4weD...,0x0426bd60e6cb9b170e4d51aa971ae4de41014968,Luxury life,Luxury life,NaN,1000000000,4.14,0.00,2025-02-23 14:23:13,0x3c42f0d3b884c027a2ce5998d09767239cc29f1d,...,eIMQkkROtQxubH~qbIkCMxRjDhxuRjogRjRikCRjayogIo...,"[{""amount"":{""currency"":{""address"":""0x000000000...",https://media.decentralized-content.com/-/rs:f...,image/jpeg,ipfs://bafybeigggf42cs3622au7jfdrt66x4cn6qaz2h...,https://media.decentralized-content.com/-/rs:f...,eaH-oV%20MM|Ip~Vt7M|R*NGoes:%1j@f6%1oeoLfQofxa...,https://media.decentralized-content.com/-/rs:f...,andr1i0784,R3JhcGhRTEFjY291bnRQcm9maWxlOjY2MDI4NjYzMDVmMD...
4,R3JhcGhRTFpvcmEyMFRva2VuOkJBU0UtTUFJTk5FVC4weD...,0x042d089f9aa1f9f4e928ed50abb94937e40a2031,Front yard 3,Front yard 3,NaN,1000000000,0.58,0.19,2025-03-31 09:16:23,0xcd60157427695e070461a4ad4af8c96b817ee721,...,eAFY_KXO?KImsE?K-VEQiwIUnXD*NIW9k6-oS0xnt0WB-m...,"[{""amount"":{""currency"":{""address"":""0x000000000...",https://media.decentralized-content.com/-/rs:f...,image/jpeg,ipfs://bafybeib7bvg7zitolcv56je5h6pqsn46qte5rn...,https://media.decentralized-content.com/-/rs:f...,"eOR^4+u,}kNyElr?Sha}$fR-,-kWElRk$zw[oyR-RRkCVu...",https://media.decentralized-content.com/-/rs:f...,azou,R3JhcGhRTEFjY291bnRQcm9maWxlOjY3ZTJhYTZmZmQ1Mj...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5885,R3JhcGhRTFpvcmEyMFRva2VuOkJBU0UtTUFJTk5FVC4weG...,0xffe38a9922d7394b6ceb365f16b858c8a1dd745e,9.03.2025 13:00,9.03.2025 13:00,NaN,1000000000,7.22,1.06,2025-03-09 10:00:21,0xe2616d2a4cb66984b89dd0ad602a6e6197fb72ec,...,"eFIrQc9brrIW^+vZ$+jc-p9Z4:E19ZWC%2^,jcI-56x[0L...","[{""amount"":{""currency"":{""address"":""0x000000000...",https://media.decentralized-content.com/-/rs:f...,image/jpeg,ipfs://bafybeihpp4nelua7znmwohwrq6qpqcnyrye3lj...,https://media.decentralized-content.com/-/rs:f...,"eiH{ThMx^*%1%f.8NGMxxZbE~VkX.8jcf+Myt6s,S5ogx]...",https://media.decentralized-content.com/-/rs:f...,muhonder,R3JhcGhRTEFjY291bnRQcm9maWxlOjY3MWEzNzAyOGRhOG...
5886,R3JhcGhRTFpvcmEyMFRva2VuOkJBU0UtTUFJTk5FVC4weG...,0xffe4e1bb20b0ffcd095b315390fd4a2bc7971e9b,Dj Chaplin,Dj Chaplin,NaN,1000000000,0.00,0.00,2025-04-03 11:44:21,0x4c7ae3f5885f24414dc55c4bd287cd0114e02232,...,eGAlz=BXi|skNG}^Otr?NGadxckWjENGn~j]spNZr?WC9]...,"[{""amount"":{""currency"":{""address"":""0x000000000...",https://media.decentralized-content.com/-/rs:f...,video/mp4,ipfs://bafybeib27z5iznu3zmekgkmvb36g2xzhzsw2o2...,https://media.decentralized-content.com/-/rs:f...,eLBW3zD*9xs.oJtRV@WCj[oe0g%1s+a#t6NGkCoeaya$t3...,https://media.decentralized-content.com/-/rs:f...,kingofeast10,R3JhcGhRTEFjY291bnRQcm9maWxlOjY3NWY4MWJiODc4Nz...
5887,R3JhcGhRTFpvcmEyMFRva2VuOkJBU0UtTUFJTk5FVC4weG...,0xfff5222443d998519f0f2ac4079d48284b20c7f6,miuw,miuw,NaN,1000000000,0.56,0.00,2025-02-23 17:20:13,0xc5e508e020e2576eb7bbeae5facc494ef5345879,...,eDGSDj0OJDoy-;_2MvDhkEM|%Mt7Dixtoxxts+oft7kEV@...,"[{""amount"":{""currency"":{""address"":""0x000000000...",https://media.decentralized-content.com/-/rs:f...,image/png,ipfs://bafybeie6qv473hfzn5oc4pvfc6lybufb6bixlq...,https://media.decentralized-content.com/-/rs:f...,exP5j5Rj.Sni%#yCj[V[bHWB.mofR6baRPofbHf6jtjZyD...,https://media.decentralized-content.com/-/rs:f...,luftwaffe,R3JhcGhRTEFjY291bnRQcm9maWxlOjY3YmI0ZTEzYjUxNG...
5888,R3JhcGhRTFpvcmEyMFRva2VuOkJBU0UtTUFJTk5FVC4weG...,0xfff73fe98bdf7d64f175daf6b243e124cf9c0a47,moral-,moral-,NaN,1000000000,1.81,1.81,2025-03-13 20:50:53,0x1003b231c073042f8e11cf716a9345b91b961219,...,eC4:Q9VBIbRPx[t.Z}bxV@oIXAadt6jZWAbwWBjDozbHRR...,"[{""amount"":{""currency"":{""address"":""0x000000000...",https://media.decentralized-content.com/-/rs:f...,image/jpeg,ipfs://bafybeibo62bvmsqctnzuxnftehye54z5bxlsm4...,https://media.decentralized-content.com/-/rs:f...,e59%hoR+01-T9u~Cs:ovRjMy?H$%$zS5M{57%1?GIq%18_...,https://media.decentralized-content.com/-/rs:f...,twingods,R3JhcGhRTEFjY291bnRQcm9maWxlOjY2ODk3NzE2ZGY1YT...
5889,R3JhcGhRTFpvcmEyMFRva2VuOkJBU0UtTUFJTk5FVC4weG...,0xfffa26b879e0a09251943ee9e0b3219b61654432,Chromaform_001,Chromaform_001,Abstract watercolor calligraphy. Physical art ...,1000000000,17871.35,0.00,2025-03-02 14:26:47,0x42fb772e57bfa4a692b794f47e6a19434e4bc798,...,e4BWY-WVLGWBz-j[fQfQfQfQGka|}rayKjfQfQfQfQfQzn...,"[{""amount"":{""currency"":{""address"":""0x000000000...",https://media.decentralized-content.com/-/rs:f...,image/jpeg,ipfs://bafybeihd25vtccoar4fo4zv6lpnwjhoa3nnku4...,https://media.decentralized-content.com/-/rs:f...,ebR2*=M{.Se.f+s:aybHfQkC*JjZMKbbV@o}f6aefkV@Q....,https://media.decentralized-content.com/-/rs:f...,mxjxn,R3JhcGhRTEFjY291bnRQcm9maWxlOjY1MjViNmU5MmVhNz...

In [9]:
# Finding the intersection based on 'id'
intersection = df_initial.merge(df_new, on='address', how='inner')

In [24]:
len(intersection)

107

In [13]:
# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("text-classification", model="cardiffnlp/twitter-roberta-base-sentiment", device = -1)

Device set to use cpu

In [21]:
pipe('goblok')

[{'label': 'LABEL_1', 'score': 0.5624879002571106}]

In [22]:
df_initial['title_sentiment'] = df_initial['name'].apply(lambda x:  [] if not x else pipe(str(x)))

In [25]:
df_comment = pd.read_csv('Comment.csv')

In [28]:
df_comment['comment_sentiment'] = df_comment['comment'].apply(
    lambda x: [] if not x else pipe(str(x), truncation=True, max_length=512)
)

In [29]:
df_comment

,id,txHash,comment,timestamp,userAddress,coinAddress,scrapedAt,updatedAt,comment_sentiment
0,000a12d4-df09-4e48-83db-0f1782d8f2c8,0x9f413daee46e38a47e488cf01a4a74ed1543209c6f79...,go,2025-03-31 04:50:41,0x27e1742bd579a3db76d669baa840841a53b15615,0x1450adbc54fc986b9a4fb207c56384aa6b1d66fa,2025-04-05 14:10:27.028,2025-04-05 14:10:27.028,"[{'label': 'LABEL_1', 'score': 0.4996267855167..."
1,000ae3fa-023c-4853-8aee-6a3cfecc7c34,0x088882f9fd048fe245e2a7b6827aad42473e682f2b94...,wen,2025-03-11 02:17:51,0xb02e42eb4db387faea9bd7dec1caee90d6434efb,0xd93dc936e60e9e275cbe6f225e9c065951b9b1d4,2025-04-05 18:14:33.63,2025-04-05 18:14:33.63,"[{'label': 'LABEL_1', 'score': 0.5206257700920..."
2,001a9ab3-6052-4d8c-97f5-33f6c8a9d4c9,0xf0971e08cefef3b097912ab7b774a2c6448d2de4bbf7...,based,2025-02-21 20:48:09,0xd1ec8245c8850a151843ce8a3afdca3b19747706,0xdc1b8f07440ec756bf820db446314ab3d1c5fa6a,2025-04-05 14:11:11.171,2025-04-05 18:14:19.286,"[{'label': 'LABEL_1', 'score': 0.5764544010162..."
3,002efc20-18c5-459a-9448-ad6df2360fcf,0xb351da43dddb08e498a4b33ab031e5996a438f5dcc6e...,nice,2025-03-18 02:31:11,0x5eeff671ef82a029c7cdc04264c845a89dc18f0b,0x9910737948144c4cb0482968c48aafe4a62874ce,2025-04-05 18:16:06.133,2025-04-05 18:16:06.133,"[{'label': 'LABEL_2', 'score': 0.6387196779251..."
4,005268cf-1c99-489b-b1ec-8e590ab3474a,0xb463252adb79c6d81a8d8418d6404398f38119cd6738...,Dino's Time 🦖🚀 bull dino's 🦖🚀,2025-03-27 12:56:21,0x9301d80b5f7c03c30a8bdc95b9c70facf735f764,0x6d51d9f8a3afe7823ecd417047c008ee2e74c609,2025-04-05 14:11:14.628,2025-04-05 14:11:14.628,"[{'label': 'LABEL_1', 'score': 0.7257707118988..."
...,...,...,...,...,...,...,...,...,...
5216,ffcbbf95-4df9-4622-aa53-458b46a9d16f,0x8f3726c313c72fae38fcb8f7f73ec857f48078a96ae8...,Create!,2025-03-10 23:00:29,0x0a6d6f90a76929b7b807c72067863b380d1fe9e0,0x8a9cf9ae6536127129727938cb1a6438273e4f94,2025-04-05 18:13:52.417,2025-04-05 18:13:52.417,"[{'label': 'LABEL_2', 'score': 0.5202958583831..."
5217,ffcd4e4c-5d2c-489e-86e7-9d3c1129a5cc,0xb4a949fde0b2092d430947fe787af34b27c2bbda6f53...,hihi,2025-03-30 19:09:13,0xd0ac50d9f7516be16e2449539394a3967bea03c7,0xa90e3869db35f7ede82cba29240287c020b51499,2025-04-05 14:10:45.99,2025-04-05 14:10:45.99,"[{'label': 'LABEL_1', 'score': 0.5879852771759..."
5218,ffe590a8-4485-4736-a08d-a68ef61a1f39,0xdd0e33c84d3782c97702f99b119a1c7ad28e3d5c5f0b...,ehwgegwq,2025-03-23 12:53:03,0xe545d13966864c4079c60b659ec293c96c6bc092,0xf1fc9580784335b2613c1392a530c1aa2a69ba3d,2025-04-05 18:12:44.95,2025-04-05 18:12:44.95,"[{'label': 'LABEL_1', 'score': 0.6271908283233..."
5219,ffe5cff2-12ce-40d2-a37d-ead58e5bc5c0,0xa60f96e4fc56d8ca1f3f63ea3f3cac99c98cf40f7101...,hehe,2025-03-19 14:25:51,0xf4e97683af29a083d1d53ba3844cca8920176ba9,0x97900ff53a3eb070ac2d7001e355fd9b606fe078,2025-04-05 14:10:13.381,2025-04-05 14:10:13.381,"[{'label': 'LABEL_2', 'score': 0.5960254073143..."
5220,fffbbe81-c852-47d6-89e2-8b108a7b62ce,0xff86e2e79a7dc4ea198658a0b6ff9413457af551cd11...,hi,2025-03-24 10:17:13,0x19e70a0db21353bc1c5e40c6e4adde28a3ec167c,0x97900ff53a3eb070ac2d7001e355fd9b606fe078,2025-04-05 14:10:02.94,2025-04-05 14:10:02.94,"[{'label': 'LABEL_1', 'score': 0.5521482825279..."